#
# Travis CI build script.
# https://travis-ci.org/kyamagu/mexplus
#

language: cpp
sudo: required
dist: xenial
compiler:
- gcc

os:
- linux

branches:
  only:
  - master

before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq octave liboctave-dev

script: octave-cli --eval "try,make test;catch e,disp(e.message);exit(1);end"
